name: Manual infra creation

on: workflow_dispatch

jobs:

  create-infra:

    name: Create terraform infra
    runs-on: ubuntu-latest

    steps:
      
      - run: export "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
      - run: export "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - run: export "TF_VAR_instance_key=${{ env.TF_VAR_INSTANCE_KEY }}"

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Terraform init
        uses: terraform init

      - name: Terraform apply
        uses: terraform apply